### ISSUE TITLE
数据集

### ISSUE THREAD

**Issue by songwenhao123** [liangjiandeng/DLPan-Toolbox#12]
您好，程序中的'TestData_qb', 'TestData_wv2', 'TestData_wv3', 'TestData_wv4',
                                     'San_Francisco_QB_RR', 'San_Francisco_QB_FR', 'NY1_WV3_FR',
                                     'NY1_WV3_RR', 'Alice_WV4_FR', 'Alice_WV4_RR', 'Rio_WV2_FR', 'Rio_WV2_RR'这些数据集可以提供一下吗，非常感谢您。

**Comment by liangjiandeng** [comment]
这个数据有版权问题，所以不能公开。因此为了方便大家能运行这个toolbox，我们自己做了一个数据集Pancollection（含多个卫星数据），相应的中文文章有详细的仿真细节，便于大家用进行统一、公平的数据集比较（配有公平的matlab测试包，和传统方法一起比较；可一键出所有比较方法（深度+传统）的比较结果+eps画图+数值指标（latex表格形式），认真阅读Toolbox介绍即可明白）。相关数据集链接为： https://github.com/liangjiandeng/PanCollection

**Comment by liangjiandeng** [comment]
中文数据细节详见：
@ARTICLE{dengjig2022,
	author={邓良剑，冉燃，吴潇，张添敬},
	journal={中国图象图形学报},
	title={遥感图像全色锐化的卷积神经网络方法研究进展},
 	year={2022},
  	volume={},
  	number={9},
  	pages={},
  	doi={10.11834/jig.220540}
   }

**Comment by songwenhao123** [comment]
感谢您的回答，我在运行02-Test-toolbox-for-traditional-and-DL(Matlab)时发现，需要使用sensor = 'WV3';
%     Qblocks_size = 32;
%     bicubic = 0;% Interpolator
%     flag_cut_bounds = 1;% Cut Final Image
%     dim_cut = 21;% Cut Final Image
%     thvalues = 0;% Threshold values out of dynamic range
%     printEPS = 0;% Print Eps
%     ratio = 4;% Resize Factor
%     L = 11;% Radiometric Resolution等参数，在您的文章中可以找到其他卫星数据集的L和ratio参数，但是其他参数没有被找到，希望您可以解答

**Comment by liangjiandeng** [comment]
这些参数都不重要，除了两个是卫星特有的：
         L = 11 （位）是针对WV3, WV2 和QB，我记得GF2是10位的，即L=10; ratio对所有卫星都是4.这些参数是卫星特有的，百度一下都可以查到。其他的都是图片打印设置，不重要。
        
            
        
    
         
        
            
                        ***@***.***
            
        
     
    
  
    ---- 回复的原邮件 ----
  
  
    
      
        
         发件人 
        
        
            ***@***.***>
            
        
      
      
        
         发送日期 
        
        
        2023年4月18日 11:22
        
      
      
        
         收件人 
        
        
         
          
            ***@***.***>
            
          
        
      
      
        
         抄送人 
        
        
          
            Liang-Jian ***@***.***>
            ,
          
          
            ***@***.***>
            
          
        
      
      
        
         主题 
        
        
              Re: [liangjiandeng/DLPan-Toolbox] 数据集 (Issue #12)
        
      
    
  

感谢您的回答，我在运行02-Test-toolbox-for-traditional-and-DL(Matlab)时发现，需要使用sensor = 'WV3';
%     Qblocks_size = 32;
%     bicubic = 0;% Interpolator
%     flag_cut_bounds = 1;% Cut Final Image
%     dim_cut = 21;% Cut Final Image
%     thvalues = 0;% Threshold values out of dynamic range
%     printEPS = 0;% Print Eps
%     ratio = 4;% Resize Factor
%     L = 11;% Radiometric Resolution等参数，在您的文章中可以找到其他卫星数据集的L和ratio参数，但是其他参数没有被找到，希望您可以解答
