### ISSUE TITLE
关于数据预处理

### ISSUE THREAD

**Issue by stxg13056** [liangjiandeng/DLPan-Toolbox#13]
您好，我最近使用该框架的时候，需要把训练后得到的模型，对训练集进行测试，比如wv3训练集的9714张数据作为测试集，但我发现测试得到的图片与标签gt相比发生了旋转之类的变化，也就是数据在测试时进行了预处理？
但奇怪的是，我在使用RR或者FR数据集进行测试的时候，就没有这种情况发生，请问我该如何保证训练集作为测试集时生成的图片不会发生变化呢？

**Comment by liangjiandeng** [comment]
同学你好，训练数据因为是保存为h5格式的（只能用h5存储(维度为：WxHxCxN)，文件太大不能用mat格式存储），在用 h5py.File读取的时候，此命令会把维度自动进行维度置换为NxCxHxW。而测试数据是NxHxWxC维度的，因此可能是这个原因。你可以用permute命令将维度进行置换为你需要的。请check 如下路径的文件：DLPan-Toolbox/01-DL-toolbox(Pytorch)/UDL/pansharpening/common/dataset.py祝好，邓良剑
        
            
        
    
         
        
            
                        ***@***.***
            
        
     
    
  
    ---- 回复的原邮件 ----
  
  
    
      
        
         发件人 
        
        
            ***@***.***>
            
        
      
      
        
         发送日期 
        
        
        2023年4月14日 10:29
        
      
      
        
         收件人 
        
        
         
          
            ***@***.***>
            
          
        
      
      
        
         抄送人 
        
        
          
            ***@***.***>
            
          
        
      
      
        
         主题 
        
        
              [liangjiandeng/DLPan-Toolbox] 关于数据预处理 (Issue #13)
        
      
    
  

您好，我最近使用该框架的时候，需要把训练后得到的模型，对训练集进行测试，比如wv3训练集的9714张数据作为测试集，但我发现测试得到的图片与标签gt相比发生了旋转之类的变化，也就是数据在测试时进行了预处理？
但奇怪的是，我在使用RR或者FR数据集进行测试的时候，就没有这种情况发生，请问我该如何保证训练集作为测试集时生成的图片不会发生变化呢？

**Comment by stxg13056** [comment]
> 同学你好，训练数据因为是保存为h5格式的（只能用h5存储(维度为：WxHxCxN)，文件太大不能用mat格式存储），在用 h5py.File读取的时候，此命令会把维度自动进行维度置换为NxCxHxW。而测试数据是NxHxWxC维度的，因此可能是这个原因。你可以用permute命令将维度进行置换为你需要的。请check 如下路径的文件：DLPan-Toolbox/01-DL-toolbox(Pytorch)/UDL/pansharpening/common/dataset.py祝好，邓良剑 ***@***.***
> […](#)
> ---- 回复的原邮件 ---- 发件人 ***@***.***> 发送日期 2023年4月14日 10:29 收件人 ***@***.***> 抄送人 ***@***.***> 主题 [liangjiandeng/DLPan-Toolbox] 关于数据预处理 (Issue #13) 您好，我最近使用该框架的时候，需要把训练后得到的模型，对训练集进行测试，比如wv3训练集的9714张数据作为测试集，但我发现测试得到的图片与标签gt相比发生了旋转之类的变化，也就是数据在测试时进行了预处理？ 但奇怪的是，我在使用RR或者FR数据集进行测试的时候，就没有这种情况发生，请问我该如何保证训练集作为测试集时生成的图片不会发生变化呢？ —Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you are subscribed to this thread.Message ID: ***@***.***>

感谢您的解答
