### ISSUE TITLE
高分二号卫星数据预处理

### ISSUE THREAD

**Issue by anxiaonuoxyz** [liangjiandeng/DLPan-Toolbox#17]
您好，首先非常感谢您的开源工作。我跑通您的代码以后想使用自己得到的高分二号数据进行实验，我从国家对地观测科学数据中心下载了一些高分二号的数据，对全色数据进行辐射定标和正射校正，对多光谱数据进行辐射定标大气校正和正射校正，但是我最终得到的全色图像数据范围是0-255，多光谱图像数据范围是0-16384也就是2的14次方，但是您的高分二号数据全色和多光谱范围都是0-1024，所以想请问您您是如何进行高分二号数据的预处理的。这个问题苦恼我许久，如果您能给我提供一些帮助我将不胜感激，非常感谢。最后再次感谢您的开源工作！谢谢！

**Comment by liangjiandeng** [comment]
我们是从一个网站下载的数据集，我记得gaofen是10位的数据，最大应该是1024. 你超出这么多是不是前期处理引起的。不过即使超出你可以归一化到0-1024上去。
        实际上代码里面有个地方需要把这些数据都归一化到0-1来输入网络计算。
        
            
        
    
         
        
            
                        ***@***.***
            
        
     
    
  
    ---- 回复的原邮件 ----
  
  
    
      
        
         发件人 
        
        
            ***@***.***>
            
        
      
      
        
         发送日期 
        
        
        2023年6月7日 13:42
        
      
      
        
         收件人 
        
        
         
          
            ***@***.***>
            
          
        
      
      
        
         抄送人 
        
        
          
            ***@***.***>
            
          
        
      
      
        
         主题 
        
        
              [liangjiandeng/DLPan-Toolbox] 高分二号卫星数据预处理 (Issue #17)
        
      
    
  

您好，首先非常感谢您的开源工作。我跑通您的代码以后想使用自己得到的高分二号数据进行实验，我从国家对地观测科学数据中心下载了一些高分二号的数据，对全色数据进行辐射定标和正射校正，对多光谱数据进行辐射定标大气校正和正射校正，但是我最终得到的全色图像数据范围是0-255，多光谱图像数据范围是0-16384也就是2的14次方，但是您的高分二号数据全色和多光谱范围都是0-1024，所以想请问您您是如何进行高分二号数据的预处理的。这个问题苦恼我许久，如果您能给我提供一些帮助我将不胜感激，非常感谢。最后再次感谢您的开源工作！谢谢！
