### ISSUE TITLE
关于训练结束和验证结束，代码不会停止

### ISSUE THREAD

**Issue by stxg13056** [liangjiandeng/DLPan-Toolbox#18]
您好，想请教一个问题！
代码里面的参数cfg.workflow，
比如设置为[('train', 1), ('val', 1)]，然后假设epoch为100，那训练完之后，代码会一直重复验证最后一轮，不会停止；
比如设置为[('train', 1)]，然后假设epoch为100，那训练完100次之后，代码会停住，但是没有结束的信号，也没有退出训练，而且显存依然被占用，但是并没有进行训练的任何动作，日志也没有更新任何多的内容。
这是由于哪一部分代码出了问题呢？
但是单独进行验证，也就是使用 ‘run_test_pansharpening.py’文件进行验证的时候， ('val', 1)，代码验证完一次就会停止。

**Comment by XiaoXiao-Woo** [comment]
仅测试和验证，应当设置cfg.eval。

**Comment by stxg13056** [comment]
还有另外一个问题就是，我看代码里面是可以设置多个优化器来更新网络参数的，不过我设计了两个优化器之后，更新会报错。
![image](https://github.com/liangjiandeng/DLPan-Toolbox/assets/81797325/6765dcfd-c011-44d7-9b0a-7caab3ce6197)
下面是优化器设计的代码以及需要更新的损失：
![image](https://github.com/liangjiandeng/DLPan-Toolbox/assets/81797325/ae0c7b5c-33c6-4e4e-9513-b64eaaf2256f)
![image](https://github.com/liangjiandeng/DLPan-Toolbox/assets/81797325/eca491ad-767c-484a-86ed-d28731d78f34)
报错部分的代码：
![image](https://github.com/liangjiandeng/DLPan-Toolbox/assets/81797325/ca232bc3-53e1-42ff-9ef8-5898ecd8faaa)
可以麻烦看一下应该如何修改吗？
