### ISSUE TITLE
运行Demo__Reduced_Resolution报错

### ISSUE THREAD

**Issue by lzm-01** [liangjiandeng/DLPan-Toolbox#28]
我选择了algorithms = {'GT','EXP','BT-H','BDSD-PC','PanNet'};
但是到了PanNet就开始报错，并且这个sr是在哪里定义的？
![sr](https://github.com/user-attachments/assets/70899b0d-9540-4f78-b4ba-a0446c7f855a)

**Comment by lzm-01** [comment]
将sr替换为如图，产生新的报错
![srr](https://github.com/user-attachments/assets/1b6a1815-18dc-4fc9-b037-9d820deee046)

**Comment by xiaowangtongxue-1** [comment]
你好，我也是这个错误，请问后面是怎么解决的呢？ @lzm-01

**Comment by lzm-01** [comment]
> 你好，我也是这个错误，请问后面是怎么解决的呢？ [@lzm-01](https://github.com/lzm-01)

你好，时间太久我已忘记。对于测试代码可以参考我TS-Pan仓库。

**Comment by xiaowangtongxue-1** [comment]
好的，麻烦啦！



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2025年9月14日(周日) 中午1:11
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [liangjiandeng/DLPan-Toolbox] 运行Demo__Reduced_Resolution报错 (Issue #28)


lzm-01 left a comment (liangjiandeng/DLPan-Toolbox#28)
  
你好，我也是这个错误，请问后面是怎么解决的呢？ @lzm-01
  
你好，时间太久我已忘记。对于测试代码可以参考我TS-Pan仓库。

**Comment by xiaowangtongxue-1** [comment]
#@你好，再次打扰您了，我运行了您仓库的代码，发现缺少psnr的脚本，可以提供一下嘛

<img width="541" height="136" alt="Image" src="https://github.com/user-attachments/assets/18addb6c-ff95-4976-ba7f-cf24a9c6f981" />

> > 你好，我也是这个错误，请问后面是怎么解决的呢？ [@lzm-01](https://github.com/lzm-01)
> 
> 你好，时间太久我已忘记。对于测试代码可以参考我TS-Pan仓库。

**Comment by lzm-01** [comment]
> #@你好，再次打扰您了，我运行了您仓库的代码，发现缺少psnr的脚本，可以提供一下嘛
> 
> <img alt="Image" width="541" height="136" src="https://private-user-images.githubusercontent.com/176649043/489362504-18addb6c-ff95-4976-ba7f-cf24a9c6f981.png?jwt=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NTc5MTI0MjgsIm5iZiI6MTc1NzkxMjEyOCwicGF0aCI6Ii8xNzY2NDkwNDMvNDg5MzYyNTA0LTE4YWRkYjZjLWZmOTUtNDk3Ni1iYTdmLWNmMjRhOWM2Zjk4MS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjUwOTE1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI1MDkxNVQwNDU1MjhaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1mMDg4MzBiZDZjMTUwZDA1ZDM2Y2Q4NTk0ZWMzYTY0YWFjMGRkNDRjZjc1NmQ3OGM2NGZlODhlZTVlM2JmNDFmJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.E3ZdvioLN-qRCNrj54ZEPRqsxO0EshZM-pvAl-acNek">
> > > 你好，我也是这个错误，请问后面是怎么解决的呢？ [@lzm-01](https://github.com/lzm-01)
> > 
> > 
> > 你好，时间太久我已忘记。对于测试代码可以参考我TS-Pan仓库。

你好，我已在仓库更新。如有其他问题，请移步至我的仓库进行说明。本issue将不再进行更新。
