### ISSUE TITLE
您好，我想请教一下这个问题！

### ISSUE THREAD

**Issue by stxg13056** [liangjiandeng/DLPan-Toolbox#3]
E:\anaconda3\python.exe "D:/My--Study/My work/DLPan-Toolbox-main/01-DL-toolbox(Pytorch)/UDL/pansharpening/run_test_pansharpening.py"
111 entrypoint
111 None
222 pansharpening
111 None
333 BDPN
D:\My--Study\My work\DLPan-Toolbox-main\01-DL-toolbox(Pytorch)\UDL\Basis\option.py:113: UserWarning: Note: FusionNet, DiCNN, PNN don't have high-pass filter
  warnings.warn(warning)
accumulated_step = 1
amp = None
amp_opt_level = 'O0'
arch = 'BDPN'
backend = 'nccl'
clip_max_norm = 0
crop_batch_size = 128
device = 'cuda'
dist_url = 'env://'
global_rank = 0
gpu_ids = [0]
launcher = 'none'
load_model_strict = True
local_rank = 0
log_dir = 'logs'
mode = None
model_style = None
once_epoch = False
reg = True
reset_lr = False
resume_mode = 'best'
rgb_range = 255
save_top_k = 5
seed = 10
start_epoch = 1
task = 'pansharpening'
tfb_dir = None
use_log = True
use_tfb = False
validate = False
scale = [1]
data_dir = '../Data/pansharpening'
best_prec1 = 10000
best_prec5 = 10000
metrics = 'loss'
save_fmt = 'mat'
taskhead = 'pansharpening'
img_range = 2047.0
best_epoch = 1
dataset = dict(train='wv3', val='NY1_WV3_RR')
epochs = 1000
eval = False
experimental_desc = 'Test'
lr = 0.0001
lr_scheduler = True
out_dir = 'D:/My--Study/My work/DLPan-Toolbox-main/01-DL-toolbox(Pytorch)/UDL//results/pansharpening'
print_freq = 50
resume_from = 'D:/My--Study/My work/DLPan-Toolbox-main/01-DL-toolbox(Pytorch)/UDL//results/pansharpening/wv3/BDPN/Test/.pth.tar'
samples_per_gpu = 8
workers_per_gpu = 0

accumulated_step = 1
amp = None
amp_opt_level = 'O0'
arch = 'BDPN'
backend = 'nccl'
clip_max_norm = 0
crop_batch_size = 128
device = 'cuda'
dist_url = 'env://'
global_rank = 0
gpu_ids = [0]
launcher = 'none'
load_model_strict = True
local_rank = 0
log_dir = 'logs'
mode = None
model_style = None
once_epoch = False
reg = True
reset_lr = False
resume_mode = 'best'
rgb_range = 255
save_top_k = 5
seed = 10
start_epoch = 1
task = 'pansharpening'
tfb_dir = None
use_log = True
use_tfb = False
validate = False
scale = [1]
data_dir = '../Data/pansharpening'
best_prec1 = 10000
best_prec5 = 10000
metrics = 'loss'
save_fmt = 'mat'
taskhead = 'pansharpening'
img_range = 2047.0
best_epoch = 1
dataset = dict(train='wv3', val='NY1_WV3_RR')
epochs = 1000
eval = False
experimental_desc = 'Test'
lr = 0.0001
lr_scheduler = True
out_dir = 'D:/My--Study/My work/DLPan-Toolbox-main/01-DL-toolbox(Pytorch)/UDL//results/pansharpening'
print_freq = 50
resume_from = 'D:/My--Study/My work/DLPan-Toolbox-main/01-DL-toolbox(Pytorch)/UDL//results/pansharpening/wv3/BDPN/Test/.pth.tar'
samples_per_gpu = 8
workers_per_gpu = 0
workflow = [('train', 50)]

dict_keys(['pansharpening', 'entrypoint', 'BDPN', 'DiCNN1', 'DRPNN', 'FusionNet', 'MSDCNN', 'PanNet', 'PNN'])
=> creating D:\My--Study\My work\DLPan-Toolbox-main\01-DL-toolbox(Pytorch)\UDL\results\pansharpening\wv3\BDPN\Test
- Set random seed to 10
E:\anaconda3\lib\site-packages\torch\nn\_reduction.py:42: UserWarning: size_average and reduce args will be deprecated, please use reduction='mean' instead.
  warnings.warn(warning.format(ret))
D:\My--Study\My work\DLPan-Toolbox-main\01-DL-toolbox(Pytorch)\UDL\AutoDL\trainer.py:86: UserWarning: config is now expected to have a `runner` section, please set `runner` in your config.
  warnings.warn(
Traceback (most recent call last):
  File "D:/My--Study/My work/DLPan-Toolbox-main/01-DL-toolbox(Pytorch)/UDL/pansharpening/run_test_pansharpening.py", line 17, in <module>
    main(cfg)
  File "D:\My--Study\My work\DLPan-Toolbox-main\01-DL-toolbox(Pytorch)\UDL\AutoDL\trainer.py", line 256, in main
    trainer(
  File "D:\My--Study\My work\DLPan-Toolbox-main\01-DL-toolbox(Pytorch)\UDL\AutoDL\trainer.py", line 194, in trainer
    runner.register_hook(
  File "D:\My--Study\My work\DLPan-Toolbox-main\01-DL-toolbox(Pytorch)\UDL\mmcv\mmcv\runner\base_runner.py", line 282, in register_hook
    assert isinstance(hook, Hook)
AssertionError
loading SingleDataset: ['../Data/pansharpening/test_data/wv3/NY1_WV3_RR.mat'] with 2047.0

Process finished with exit code 1

**Comment by stxg13056** [comment]
Thanks for reminding me that I have solved this problem. I have another question. How do I visualize the generated. mat file?

**Comment by XiaoXiao-Woo** [comment]
You can use showimage8 in postprocess.py
<https://github.com/XiaoXiao-Woo/PanCollection/blob/dev/UDL/Basis/postprocess.py>
to
visualize MS image.

stxg13056 ***@***.***> 于2022年10月6日周四 16:26写道：

**Comment by stxg13056** [comment]
Thanks！
