### ISSUE TITLE
你好请问一下这里的psnr值是否计算有误呢，我在训练的过程中，psnr值一直在下降

### ISSUE THREAD

**Issue by lyl201361** [liangjiandeng/DLPan-Toolbox#5]
![image](https://user-images.githubusercontent.com/45712218/200304465-295a5af9-fd1e-4350-9bbb-b5acf0809ead.png)
![image](https://user-images.githubusercontent.com/45712218/200304650-cc62f433-910d-41d7-8f3d-2beec14c13ba.png)
下面是我找的一个计算psnr值的方法，用这个方法在训练的过程中，psnr值会随着训练上升
![image](https://user-images.githubusercontent.com/45712218/200304840-b3124c01-25cf-48e9-99ef-fadf7dc2276f.png)
![image](https://user-images.githubusercontent.com/45712218/200304935-9f0b0281-ae20-4e57-a49b-89e88a0fac21.png)

**Comment by XiaoXiao-Woo** [comment]
Thanks for your issue. I have updated the code, please see https://github.com/liangjiandeng/DLPan-Toolbox/commit/3974cea0ba3844bbfa71943141989344a22ea4ba. In fact, you should utilize matlab code to calcalute indicators. PSNR is not commonly used for Pansharpening.
