### ISSUE TITLE
How to visualize mat file?

### ISSUE THREAD

**Issue by ysd1111** [liangjiandeng/DLPan-Toolbox#7]
I have tested the model you provided, but I cannot see the visual effect. How do you batch visualize these results files when doing experiments? May be a trouble?

**Comment by XiaoXiao-Woo** [comment]
you can see https://github.com/liangjiandeng/DLPan-Toolbox/blob/f570f798d6fc8b3e1505a0136c51a743d2d62512/01-DL-toolbox(Pytorch)/UDL/Basis/python_sub_class.py#L216 in python or save mat to test and view inn DLPan-Toolbox.

**Comment by ysd1111** [comment]
Thx. And sorry to bother you again. But I have another one question.
I noticed that in the **'dataset.py'** file, when loading data, we need to divide by an img_scale (like **gt/img_scale**). I'd like to know what is the main purpose of this step.

**Comment by XiaoXiao-Woo** [comment]
img_range (a.k.a img_scale) is used to normalize image to 0-1.
