### ISSUE TITLE
Some questions about the building of the dataset and visualizing the results

### ISSUE THREAD

**Issue by anxiaonuoxyz** [liangjiandeng/DLPan-Toolbox#8]
Hello, thank you very much for your work, the tool you proposed is practical and effective, but I would like to ask you, how can I use the data pictures which is I collected to build.h5 files in the data set?

In addition, I used the save_results function in ps_evaluation.py file to save the fusion result file, but the obtained png image display results are not satisfactory(The result is shown below). May I ask how do you visualize the results of the model?

![M2@2XPRD_I4OXLS8J@IUE{O](https://user-images.githubusercontent.com/52534886/203512024-c0cc1e93-c254-4766-96b0-fc9bcb2d8e18.png)

I would appreciate it if you could answer my questions

**Comment by XiaoXiao-Woo** [comment]
First, for build_h5 in your dataset, I think you can use direct Dataloader provided by Pytorch if you don't need faster train your model. If you want to build h5 files, you can refer to matlab code (https://github.com/liangjiandeng/DLPan-Toolbox/blob/f570f798d6fc8b3e1505a0136c51a743d2d62512/03-Data-Simulation(Matlab)/Demo_DataSimu_qb.m#L151) or search these related codes in github.

**Comment by anxiaonuoxyz** [comment]
Thank you very much for your answer. I checked the relevant code and found that I set cfg.img_range=2047.0, but I still did not get an intuitive visual result. Please ask if you have any solutions
